package cardsagainstdiscord

func init() {
	Packs["main"] = &CardPack{
		Prompts: []PromptCard{
			{`%s + %s = %s.`, 3},
			{`%s is a slippery slope that leads to %s.`, 2},
			{`%s would be woefully incomplete without %s.`, 2},
			{`%s: good to the last drop.`, 1},
			{`%s: kid tested, mother approved.`, 1},
			{`%s: kid-tested, mother-approved.`, 1},
			{`%s: Once you pop, the fun don't stop!`, 1},
			{`%s? Jim'll fix it!`, 1},
			{`%s? There's an app for that.`, 1},
			{`%s? Yeah, nah.`, 1},
			{`%s. Awesome in theory, kind of a mess in practice.`, 1},
			{`%s. Betcha can't have just one!`, 1},
			{`%s. High five, bro.`, 1},
			{`%s. It's a trap!`, 1},
			{`%s. That was so metal.`, 1},
			{`%s. That's how I want to die.`, 1},
			{`%s. That's why mums go to Iceland.`, 1},
			{`★✰✰✰✰ Do NOT go here! Found %s in my Kung Pao chicken! `, 1},
			{`50%% of all marriages end in %s.`, 1},
			{`A recent laboratory study shows that undergraduates have 50%% less sex after being exposed to %s.`, 1},
			{`A remarkable new study has shown that chimps have evolved their own primitive version of %s.`, 1},
			{`A romantic candlelit dinner would be incomplete without %s.`, 1},
			{`A romantic, candlelit dinner would be incomplete without %s.`, 1},
			{`A successful job interview begins with a firm handshake and ends with %s.`, 1},
			{`ABC presents: "%s: The Story of %s."`, 2},
			{`After eight years in the White House, how is Obama finally letting loose?`, 1},
		},
		Responses: []ResponseCard{
			"Tweeting.",
			"(I am doing Kegels right now.)",
			"10,000 Syrian refugees.",
			"100% Pure New Zealand.",
			"2 Girls 1 Cup.",
			"400 years of colonial atrocities.",
			"50 mg of Zoloft daily.",
			"50,000 volts straight to the nipples.",
			"72 virgins.",
			"8 oz. of sweet Mexican black-tar heroin.",
			"A bag of magic beans.",
			"A balanced breakfast.",
			"A ball of earwax, semen, and toenail clippings.",
			"A big black dick.",
			"A big hoopla about nothing.",
			"A bird that shits human turds.",
			"A bit of slap and tickle.",
			"A bitch slap.",
			"A bleached arsehole.",
			"A bleached asshole.",
			"A Bop It™.",
			"A bowl of mayonnaise and human teeth.",
			"A brain tumor.",
		},
	}
}
